### ISSUE TITLE
Overflow and x-sidescrolling on mobile

### ISSUE THREAD

**Issue by Roosted7** [EmielH/hallo-hugo#13]
Hi Emiel!
I really like your simple theme, but I think I found a small bug (or at last lack of documentation :p )

If the portrait image is larger than the 300x300 example, the page doesn't render nicely on small viewports (phones). It will enable a side scrollbar and put the portrait picture offcentre. It would be nice if that could be improved - or at least recommend people to only use 300x300.

**Comment by Roosted7** [comment]
Just found out, it still does it if the viewport is small enough (even on the demo page)

**Comment by EmielH** [comment]
Hi, thank you for your kind words!

I cannot reproduce the behaviour you're describing on the newest version of the theme. [This recent commit](https://github.com/EmielH/hallo-hugo/commit/d92837df07fdf3bf8c927fd523036b3d2a0b1412) should make the portrait image scale on smaller viewports.

I did see it happening on the demo page on the theme site, though, so I guess the theme site hasn't updated to the latest version of this theme yet. Could you check whether this still happens with the newest version?

**Comment by Roosted7** [comment]
You're right! It is fixed :)

Sorry - somehow I had 2.3.0 checked out, instead of the master... Thanks for your quick response!
