### ISSUE TITLE
Support for other protocols in links

### ISSUE THREAD

**Issue by metbril** [EmielH/hallo-hugo#17]
I want to use `tel:`, `skype:` or `whatsapp://` links in the homepage. Those are stripped by Hugo. To prevent this, the `.url` variable needs to be post-processed by the `safeURL` function.
 
This is the current code:

https://github.com/EmielH/hallo-hugo/blob/0e587d11371468d7296588ab99ab65da9aedd36a/layouts/index.html#L19

    href="{{ .url }}"

should become

    href="{{ .url | safeURL }}"

**Comment by EmielH** [comment]
Thanks for bringing this to my attention! I will look into this as soon as I have a bit of spare time.

**Comment by EmielH** [comment]
@metbril I committed a fix for this. Could you check if this solves your problem? Thanks a lot!

**Comment by metbril** [comment]
I don't have access to a computer this week. Phone only. I'll chime back in asap.

**Comment by patrickderitter** [comment]
Hi @EmielH and @metbril, as I needed this support for a project as well, I tested this and can confirm this works.

**Comment by EmielH** [comment]
Thanks a lot! 👍  I'll close this now.
