### ISSUE TITLE
Unable to change the color with changes in config.toml

### ISSUE THREAD

**Issue by inashivb** [EmielH/hallo-hugo#26]
Hello!

Thank you for this simple yet pretty theme. :) I was wondering if I could get some help about changing the color of background and foreground?
I tried putting the following block in `[params]` section but it does not come into the effect. There is also no error as specified in the README.
```toml
   [params.colors]
        background = "#3f1c66"
        foreground = "#d8d517"
        hover = "#e9dafa"
```
However, I do get the following warnings on running the server. Are these related to my issue?
```shell
WARN 2021/07/05 12:49:23 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/07/05 12:49:23 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/07/05 12:49:23 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/07/05 12:49:23 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

Thank you very much!

**Comment by EmielH** [comment]
Thanks for your kind words!

On first sight, the settings in config.toml look correct. Do you have a repository that I can clone so that I can have a look?

**Comment by inashivb** [comment]
> Thanks for your kind words!
> 
> On first sight, the settings in config.toml look correct. Do you have a repository that I can clone so that I can have a look?

Thank you so much, @EmielH ! This is the repo: https://github.com/inashivb/test-webpage

**Comment by EmielH** [comment]
I don't have time today, I'll have a look soon!

**Comment by inashivb** [comment]
> I don't have time today, I'll have a look soon!

No problem at all. Please take your time! Have a good day! :)

**Comment by EmielH** [comment]
Hi @inashivb - apologies for the delay.

I cloned your repository and tried changing the colours in the config file. Everything works perfectly for me. I see a purple background and yellow letters. Also the colours update automatically when `hugo serve` is running and I change the config file.

I also see the warnings but these shouldn't be related to this issue. I'll see if there's something I can do in the theme to get rid of the warnings.

Could you please try again?

**Comment by inashivb** [comment]
Hi @EmielH !
Major apologies for getting back so late. I still do not see the changes but since the issue is unrelated to the theme and a "does not work on my machine" kind, I'll close this.
Thank you very much for taking out time to assist!
