### ISSUE TITLE
Can you change the Title that says "Hello." ?

### ISSUE THREAD

**Issue by alexserver** [EmielH/hallo-hugo#5]
I was checking the documentation.
In config.toml, when you change the var title, it only modifies the Window title...

**Comment by alexserver** [comment]
I see you cannot.
https://github.com/EmielH/hallo-hugo/blob/master/layouts/index.html#L8

**Comment by EmielH** [comment]
@alexserver I just added an option to alter the greeting. Check [the readme](https://github.com/EmielH/hallo-hugo/blob/master/README.md) for more details. Could you please verify that this works for you? Thanks!
