### ISSUE TITLE
Cannot deploy the site

### ISSUE THREAD

**Issue by iamrajiv** [EmielH/hallo-hugo#9]
```
C:\Users\Rajiv>cd Desktop
C:\Users\Rajiv\Desktop>cd site
C:\Users\Rajiv\Desktop\site\themes>
C:\Users\Rajiv\Desktop\site\themes>git clone https://github.com/EmielH/hallo-hugo.git
```
After using above command and configuring `config.toml` by adding the line `theme = "hallo"` and running `hugo server` it shows error
```
C:\Users\Rajiv\Desktop\site>hugo server
Error: Unable to find theme Directory: C:\Users\Rajiv\Desktop\site\themes\hallo
```

The problem is that when I cloned the repo in `themes` directory it saves with name `hallo-hugo` not with name `hallo` but we have configure `config.toml` with  line `theme = "hallo"` I think it should be configure with  line `theme = "hallo-hugo"` or the other solution is to rename the `hallo-hugo` repo to `hallo`. 

I think changing  line `theme = "hallo"` to  line `theme = "hallo-hugo"` in  `config.toml` will be much better

**Comment by EmielH** [comment]
Please read the instructions carefully. They say:

> If your site is also under version control using git, the easiest way to install this theme is to add it as a submodule. If you have not created a git repo for your project yet, you need to run `git init` beforehand. Inside the folder of your Hugo site, run the following command.
> 
> ```
> git submodule add https://github.com/EmielH/hallo-hugo.git themes/hallo
> ```
> 
> Alternatively, you can clone the theme into your project.
> 
> ```
> git clone https://github.com/EmielH/hallo-hugo.git themes/hallo
> ```

You forgot the `themes/hallo` part at the end.

**Comment by iamrajiv** [comment]
@EmielH yeah I did not notice that thanks for help
